apiVersion: v1
kind: Service
metadata:
    name: "myaksclister-737d"
    labels:
        app: "myaksclister-737d"
spec:
    type: LoadBalancer
    ports:
    - port: 234
      targetPort: 234
      protocol: TCP
      name: http
    selector:
        app: "myaksclister-737d"