on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: myconreg75.azurecr.io
        username: ${{ secrets.acr_myconreg75_username }}
        password: ${{ secrets.acr_myconreg75_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/examples/compose/app" -f  "examples/compose/app/Dockerfile" -t myconreg75.azurecr.io/myaksclister:${{ github.sha }} --label dockerfile-path=examples/compose/app/Dockerfile
        docker push myconreg75.azurecr.io/myaksclister:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaksclister_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksclister8ba2 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksclister8ba2`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksclister8ba2
        container-registry-url: myconreg75.azurecr.io
        container-registry-username: ${{ secrets.acr_myconreg75_username }}
        container-registry-password: ${{ secrets.acr_myconreg75_password }}
        secret-name: myaksclisterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksclister8ba2
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
        images: |
          myconreg75.azurecr.io/myaksclister:${{ github.sha }}
        imagepullsecrets: |
          myaksclisterdockerauth
